name: MLflow CI Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Conda Environment from conda.yaml
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: '3.12'
        activate-environment: movie-recommender-ci-env
        # Asumsi conda.yaml ada di dalam MLProject
        environment-file: MLProject/conda.yaml 
        use-only-tar-bz2: true

    # --- LANGKAH DIAGNOSTIK BARU DITAMBAHKAN DI SINI ---
    - name: List all files in the repository
      run: ls -R # Perintah 'ls -R' akan menampilkan semua file dan folder secara rekursif

    - name: Run Python Training Script
      run: python MLProject/modelling.py # Kita biarkan ini dulu, mungkin akan gagal lagi

    - name: Upload mlruns directory
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: mlruns-output
        path: mlruns/
