name: MLflow CI Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Conda Environment from conda.yaml
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: '3.12'
        # Nama environment harus sama dengan 'name' di conda.yaml
        activate-environment: movie-recommender-ci-env 
        # Path ke file environment Anda (jika ada di root)
        environment-file: conda.yaml
        use-only-tar-bz2: true

    - name: Display Conda and Python info
      run: |
        conda info
        which python

    # --- BAGIAN YANG DIPERBAIKI ---
    - name: Run Python Training Script
      run: python modelling.py # <-- Menjalankan skrip dari root

    # --- BAGIAN YANG DIPERBAIKI ---
    - name: Upload mlruns directory
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: mlruns-output
        path: mlruns/ # <-- Mengambil mlruns dari root
