name: MLflow CI Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Conda Environment from conda.yaml
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: '3.12'
        activate-environment: movie-recommender-ci-env 
        # --- PERBAIKAN 1: Path ke conda.yaml ---
        environment-file: MLProject/conda.yaml # Menunjuk ke file di dalam folder MLProject
        use-only-tar-bz2: true

    - name: Display Conda and Python info
      run: |
        conda info
        which python

    # --- PERBAIKAN 2: Path ke modelling.py ---
    - name: Run Python Training Script
      run: python MLProject/modelling.py # Menjalankan skrip dari dalam folder MLProject

    - name: Upload mlruns directory
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: mlruns-output
        # mlruns akan dibuat di root repository karena CWD tidak berubah
        # Jadi path ini seharusnya sudah benar
        path: mlruns/
