name: MLflow Train Workflow

on:
  push:
    paths:
      - 'MLProject/**'
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.9
        environment-file: MLProject/conda.yaml
        activate-environment: movie-recommender-env

    - name: Install MLflow
      run: |
        pip install mlflow

    - name: Run MLflow Project
      run: |
        mlflow run MLProject
